# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20161220_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='IssueComment',
        ),
    ]
