# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20161220_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_new',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='is_new',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
